In [1]:
using CSV

In [161]:
using Pkg;

In [88]:
Pkg.add("CSV");

 Resolving package versions...
  Updating `C:\Users\scott\.julia\environments\v1.0\Project.toml`
 [no changes]
  Updating `C:\Users\scott\.julia\environments\v1.0\Manifest.toml`
 [no changes]


In [2]:
games=CSV.read("C:/Users/scott/Documents/BigTen.csv")

24×4 DataFrames.DataFrame
│ Row │ Home           │ Visitor        │ HomePoints │ VisitorPoints │
│     │ String         │ String         │ Int64      │ Int64         │
├─────┼────────────────┼────────────────┼────────────┼───────────────┤
│ 1   │ Iowa           │ Northwestern   │ 20         │ 0             │
│ 2   │ Wisconsin      │ Ohio State     │ 7          │ 38            │
│ 3   │ Illinois       │ Purdue         │ 24         │ 6             │
│ 4   │ Penn State     │ Michigan State │ 28         │ 7             │
│ 5   │ Indiana        │ Nebraska       │ 9          │ 14            │
│ 6   │ Maryland       │ Minnesota      │ 10         │ 52            │
│ 7   │ Ohio State     │ Northwestern   │ 52         │ 3             │
│ 8   │ Wisconsin      │ Illinois       │ 23         │ 24            │
│ 9   │ Purdue         │ Iowa           │ 20         │ 26            │
│ 10  │ Indiana        │ Maryland       │ 34         │ 28            │
⋮
│ 14  │ Maryland       │ Purdue         │ 14         │ 40            │
│ 15  │ Michigan       │ Illinois       │ 42         │ 25            │
│ 16  │ Michigan State │ Wisconsin      │ 0          │ 38            │
│ 17  │ Penn State     │ Iowa           │ 17         │ 12            │
│ 18  │ Nebraska       │ Minnesota      │ 7          │ 34            │
│ 19  │ Maryland       │ Rutgers        │ 48         │ 7             │
│ 20  │ Iowa           │ Michigan       │ 3          │ 10            │
│ 21  │ Purdue         │ Penn State     │ 7          │ 35            │
│ 22  │ Illinois       │ Minnesota      │ 17         │ 40            │
│ 23  │ Northwestern   │ Nebraska       │ 10         │ 13            │
│ 24  │ Michigan State │ Ohio State     │ 10         │ 34            │

In [3]:
games.Home

24-element CSV.Column{String,String}:
 "Iowa"          
 "Wisconsin"     
 "Illinois"      
 "Penn State"    
 "Indiana"       
 "Maryland"      
 "Ohio State"    
 "Wisconsin"     
 "Purdue"        
 "Indiana"       
 "Minnesota"     
 "Michigan"      
 "Rutgers"       
 "Maryland"      
 "Michigan"      
 "Michigan State"
 "Penn State"    
 "Nebraska"      
 "Maryland"      
 "Iowa"          
 "Purdue"        
 "Illinois"      
 "Northwestern"  
 "Michigan State"

Let's gather the teams from the provided data and not hard code a predetermined list.  A set in Julia will give us a unique list of teams.

In [4]:
teams=Set(vcat(games.Home, games.Visitor))

Set(["Nebraska", "Purdue", "Illinois", "Maryland", "Michigan", "Northwestern", "Iowa", "Minnesota", "Penn State", "Rutgers", "Wisconsin", "Indiana", "Michigan State", "Ohio State"])

In [5]:
teamIndex=Dict(pop!(teams) => i for i=1:length(teams))

Dict{String,Int64} with 14 entries:
  "Nebraska"       => 1
  "Purdue"         => 2
  "Illinois"       => 3
  "Maryland"       => 4
  "Michigan"       => 5
  "Northwestern"   => 6
  "Iowa"           => 7
  "Minnesota"      => 8
  "Penn State"     => 9
  "Rutgers"        => 10
  "Wisconsin"      => 11
  "Indiana"        => 12
  "Michigan State" => 13
  "Ohio State"     => 14

In [6]:
teamIndex["Iowa"]

7

In [21]:
A = zeros(length(games.Home), length(teamIndex));

In [22]:
b=zeros(length(games.Home)+1);

In [23]:
for i = 1:length(games.Home)
    homeIndex = teamIndex[games.Home[i]]
    visitorIndex = teamIndex[games.Visitor[i]]
    delta::Float64 = games.HomePoints[i] - games.VisitorPoints[i]
    A[i,visitorIndex] = -1
    A[i,homeIndex] = 1
    b[i] = delta;
end

In [24]:
A

24×14 Array{Float64,2}:
  0.0   0.0   0.0   0.0   0.0  -1.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   1.0   0.0   0.0  -1.0
  0.0  -1.0   1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      1.0   0.0   0.0   0.0  -1.0   0.0
 -1.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   1.0   0.0   0.0
  0.0   0.0   0.0   1.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -1.0      0.0   0.0   0.0   0.0   0.0   1.0
  0.0   0.0  -1.0   0.0   0.0   0.0      0.0   0.0   1.0   0.0   0.0   0.0
  0.0   1.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   0.0   0.0      0.0   0.0   0.0   1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  …   0.0  -1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   1.0   0.0     -1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   1.0   0.0  -1.0   0.0   0.0
 

We have only set conditions on the differences between the teams.  We make up
an arbitrary rule that the ratings must total zero.  This condition
is expressed as the last rule.

In [25]:
A=vcat(A, transpose(ones(14)));

In [26]:
b

25-element Array{Float64,1}:
  20.0
 -31.0
  18.0
  21.0
  -5.0
 -42.0
  49.0
  -1.0
  -6.0
   6.0
  35.0
  -7.0
 -35.0
 -26.0
  17.0
 -38.0
   5.0
 -27.0
  41.0
  -7.0
 -28.0
 -23.0
  -3.0
 -24.0
   0.0

In [27]:
ratings = A\b

14-element Array{Float64,1}:
  -9.67292291017554  
  -3.3491278189530993
   4.712241805261956 
 -18.51332821117989  
  16.03893897845583  
 -14.118962013996773 
   7.7950848551223   
  15.430403093667486 
  18.609490274983237 
 -41.80437830923659  
  11.728752967877597 
 -11.330209810197333 
  -7.046934914692088 
  31.52095201306291  

In [28]:
ratings[teamIndex["Ohio State"]] - ratings[teamIndex["Michigan"]]

15.482013034607082

In [29]:
prediction(a,b)= ratings[teamIndex[a]] - ratings[teamIndex[b]]

prediction (generic function with 1 method)

In [30]:
prediction("Michigan", "Ohio State")

-15.482013034607082

In [31]:
prediction("Michigan State", "Michigan")

-23.085873893147916

In [32]:
prediction("Michigan", "Maryland")

34.552267189635714

In [35]:
prediction("Purdue", "Nebraska")

6.323795091222441